sudo: required
services:
  - docker

before_install:
  - docker build -t jmsajib11/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jmsajib11/react-test npm test -- --coverage

after_success:
  - docker build -t jmsajib11/multi-client ./client
  - docker build -t jmsajib11/multi-nginx ./nginx
  - docker build -t jmsajib11/multi-server ./server
  - docker build -t jmsajib11/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jmsajib11/multi-client
  - docker push jmsajib11/multi-nginx 
  - docker push jmsajib11/multi-server
  - docker push jmsajib11/multi-worker